### ISSUE TITLE
Can you add nosql scylla support?

### ISSUE THREAD

**Issue by denisgolius** [cube2222/octosql#112]
https://github.com/scylladb/gocqlx

**Comment by cube2222** [comment]
Hey, we're planning to add cassandra support, which would also probably solve scylla support.

**Comment by denisgolius** [comment]
> Hey, we're planning to add cassandra support, which would also probably solve scylla support.

Nice to hear this :D

**Comment by JasiekChomiak** [comment]
Closing since I opened the Cassandra support issue.

**Comment by cube2222** [comment]
#114 linking :)
