### ISSUE TITLE
Add a Schema Compare Feature

### ISSUE THREAD

**Issue by danhlee329** [cube2222/octosql#125]
This feature will be very helpful in generating sync-scripts that can allow you to compare different aspects or all of the schema where you can run that script to match the target schema.  I've used a tool that did this (which was solid), but the licensing fees were absurd.

**Comment by cube2222** [comment]
Hey, sorry, I don't understand what you're describing.

**Comment by danhlee329** [comment]
### Potential Use Case:

You have a `DEV` and `TEST` database.  You've made changes on `DEV` (i.e., column change, added/removed indexes, added a relationship, added data to a lookup table) and would like to migrate those changes to `TEST`.

#### Possible Usage of Feature:

You are able to select two databases to compare and generate sync-scripts that will automatically sync up a database to match the schema of another database. Per potential use case above, we have the `target` database being `TEST`, and we want to generate a script that we can run on the `target` database that will match it to the `original` database (that being `DEV`).  After running the sync-script in `TEST`, the schema should then match the schema on `DEV`.

When comparing databases, it'll be nice to be able to select what you want to compare on.  For instance, it'll be useful to have selections on what we can compare against in the schema (either compare on table column definitions, indices, data itself, relationships, etc).  Afterwords, all we have to do is run the neatly-packaged script in the `target` database.

**Comment by cube2222** [comment]
Thanks for the explanation! However, I don't see how this would fit into OctoSQL, as OctoSQL is mean for read-only data analysis.
