### ISSUE TITLE
Support Excel (.xlsx) files as a Datasource

### ISSUE THREAD

**Issue by MateuszKubuszok** [cube2222/octosql#130]
Seeing how useful is to be able to query with SQL in Excel and similar spreadsheets it would be useful to bring this functionality into a CLI tooling.

**Comment by cube2222** [comment]
Hey, yea, xlsx support would be a great addition I'd love to have.

Just tested out https://github.com/360EntSecGroup-Skylar/excelize and using it is straightforward. Should be a copy-paste of the CSV support.

It probably makes sense to default to a table positioned directly in the left upper corner, but provide configuration parameters allowing to use tables whose left upper corner is somewhere else.

Same for sheets, default to the first one, allow to configure others.

**Comment by cube2222** [comment]
CSV support is there, so I'm changing the title. (change back if u want)

**Comment by MateuszKubuszok** [comment]
I guess for start assuming that whole sheet is a table is ok, once the basic functionality is there anyone could extend it by e.g. picking some subregion or something.

**Comment by cube2222** [comment]
Done and released :)
