### ISSUE TITLE
Add mongoDB support

### ISSUE THREAD

**Issue by willy140198** [cube2222/octosql#155]

**Comment by will2love** [comment]
可以交流下吗 最近我也在做这个 也需要mongo的支持

**Comment by cube2222** [comment]
> 可以交流下吗 最近我也在做这个 也需要mongo的支持

I'm sorry, I do not speak chinese.

Anyways, MongoDB support is definitely something we want to have in the future, but it's not a priority for us now, so no ETA.

Feel free to contribute it and let us know if you need help with it!

**Comment by will2love** [comment]
What should I do if I need to add mongodb support base octosql

**Comment by cube2222** [comment]
Here's the readme for contributing new databases: https://github.com/cube2222/octosql/blob/master/storage/README.md

Feel free to ask follow up questions here in case you need any help, or something's not clear.

**Comment by will2love** [comment]
if I want add support  'having' operation， Do I need modify sqlParser module ?  this module can parse all sql now?

your sqlParse module reference https://github.com/xwb1989/sqlparser ??

**Comment by cube2222** [comment]
Our parser is a customized copy of the one in vitess. It's in the source code.

However, there's the parser.go file which translates between the output of the SQL parser and our logical plan. HAVING expressions are currently parsed by the SQL parser, but are ignored in parser.go. So you'd probably just have to add an additional filter node after the group by there based on the having clause, and all would work.

Though just to inform, you can simulate having using a subquery:
select * from (select c.owner, count(*) as howmany from cats c) g where g.howmany > 5

**Comment by will2love** [comment]
Thank you for your reply above
1. when type is "redis " in octosql.yaml, what is this databaseKeyName?  when I config anyone words Example “abcd” or "xxxx",  then test is ok. so this databaseKeyName what it means? 

my redis have 3 hash variable:
hset myhash1  id 1
hset myhash name  "will"

hset myhash2  id 2
hset myhash name  "tom"

hset myhash3  id 3
hset myhash name  "lily"

octoi.yaml: 
  - name: people
    type: redis
    config:
      address: "10.1.8.11:4300"
      password: "Nfsqydt"
      databaseIndex: 15
      databaseKeyName: "abcd"
  - name: mysql_test
    type: mysql
    config:
      address: "10.1.8.11:3306"
      user: "test"
      password: "123456"
      databaseName: di_abtest
      tableName: test_config

$ ./main.exe  "SELECT p.name, b.test_id, b.test_name FROM mysql_test b JOIN people p ON b.id = int(p.id)" -o json
[{"b.test_id":"page_10001","b.test_name":"实验","p.name":"will"}
]

so the databaseKeyName How to configure it use my example
and redis can config more one? 

2. What should I do if I need to add redis support String type

**Comment by will2love** [comment]
Follow the above configuration , redis query can scan all hash varibale ? but some hash variable struct is not same, and program will error when not find field . so  how use redis config?

**Comment by cube2222** [comment]
1.
The databaseKeyName is how the column with the primary key is called in octosql for this datasource. It's just "key" by default. This column would contain myhash1, myhash2, myhash3. So with your databaseKeyName "abcd" you could write a query
```
SELECT * FROM people p WHERE p.abcd = 'myhash2'
```
Redis only support lookup by this key, so filtering by values of the hash happens in memory in octosql.

2. I don't think I understand. All values coming out of redis are strings.

3. I'm not sure what you mean, here I have hashes with varying fields, and I just get nulls in the lacking places:
```
func TestName(t *testing.T) {
	client := redis.NewClient(
		&redis.Options{
			Addr:     "localhost:6379",
			Password: "",
			DB:       0,
		},
	)

	client.HSet("id", "name", "jacob").Result()
	client.HSet("id", "age", "3").Result()
	client.HSet("id", "city", "warsaw").Result()
	client.HSet("id2", "name", "wojtek").Result()
	client.HSet("id2", "age", "5").Result()
}
```

```
> octosql  'select * from people2 p'
+-------+-------+----------+----------+
| p.key | p.age |  p.name  |  p.city  |
+-------+-------+----------+----------+
| 'id2' | '5'   | 'wojtek' | <null>   |
| 'id'  | '3'   | 'jacob'  | 'warsaw' |
+-------+-------+----------+----------+
```

```
> octosql  'select p.key, p.city from people2 p'
+-------+----------+
| p.key |  p.city  |
+-------+----------+
| 'id2' | <null>   |
| 'id'  | 'warsaw' |
+-------+----------+
```

In your case, p.key would be p.abcd

**Comment by will2love** [comment]
thanks , now I kows  how use databaseKeyName.

My test: 
# set abc “this is a string value”  //redis set 

$ ./main.exe "select p.id, p.name from people p where p.key = 'abc'" -o json
2019/12/25 19:33:28 couldn't run plan: couldn't get next record: couldn't get source record: couldn't get source record: could't get hash for key abc: WRO
NGTYPE Operation against a key holding the wrong kind of value

this error is because not support other varibale  type except hash?

What should I do if I need to add redis support query redis key ‘abc’?

**Comment by will2love** [comment]
I will delete your cobra CLI , then input sql and call parse function directly,  Multiple concurrent execute sql do  will cause probmles ? Example 10000 client call same sql "select * from t" use parse func  at the same time ?

**Comment by cube2222** [comment]
Yeah, only hashes are supported. You can filter on the key or hash fields. The key filter will be pushed down to redis (only the wanted data will be transfered) and the hash fields filter will be done in-memory (all redis data will be scanned and processed in OctoSQL).

**Comment by will2love** [comment]
`(all redis data will be scanned and processed in OctoSQL)`

if a  high number of redis value, and now many client query redis value at same time,  Do will memory can crash ?

**Comment by cube2222** [comment]
It shouldn't. Everything works in a streaming fashion.

**Comment by will2love** [comment]
I do not quite understand these concepts:   `primary or secondary keys`  or `streaming`  or `filters` when I support mongo datasource .  and your streaming fashion  do refer to spark streaming or some straming frame?   Can you help me explain these to me? thanks

**Comment by cube2222** [comment]
Primary keys are primary keys in databases. Secondary keys are all other fields.

If you can push down an operation on a primary key, then it'll check the name of the field in the filter expression to see if it can push it down.

If you can push down an operation on a secondary key, then it will be pushed down regardless of the field name.

I don't undesrstand the rest of the questions.

However, overall it's best to copy&paste an existing datasource and modify it.
For greater understanding checkout the existing tests and go through them with a debugger to see how everything fits together.

**Comment by will2love** [comment]
I do not quit understand these function: `NewKeyFormula`  or `physical.Predicate` when I copy the storage/redis/datasource.go and modify it to suport mongodb. can you help me explain it? thanks

**Comment by will2love** [comment]
I support query to mongodb  ， only support sql  'and' formula 。but when use sub query to mongo ，I do not get successful result , I do not kown what is the wrong:

my test :  
select d2.age,d2.user_id, r.user_id, d2.car_tag, r.rt_leatest_product_code, 
r.rt_leatest_proposal_time  
from (select * from dws_recommend d where d.age =18) d2 
join rt_user_info r on d2.user_id = r.user_id 


result is :
  "{\"d2.age\":18,\"d2.car_tag\":0,\"d2.user_id\":\"0055a49f64b4491ca2286d1e6c5fa\",\"r.rt_leatest_product_code\":\"PH01\",\"r.rt_leatest_proposal_time\":1577024455,\"r.user_id\":\"0055a49f64b4491ca2286d1e6c5fa\"}",
            "{\"d2.age\":30,\"d2.car_tag\":1,\"d2.user_id\":\"bbade3a22005473ab83c788e478dfa0a\",\"r.rt_leatest_product_code\":\"LH11\",\"r.rt_leatest_proposal_time\":1577024455,\"r.user_id\":\"bbade3a22005473ab83c788e478dfa0a\"}"


why get the d2.age = 30 ? but my sub query is age = 18

Look forward to your reply

**Comment by cube2222** [comment]
No idea, it's your code which I have no access to. I'd speculate you're misshandling filter pushdown, but I don't know.

**Comment by cube2222** [comment]
Feel free to open a PR if you want assistance with the code.

**Comment by will2love** [comment]
sql: select *  from (select * from dws_recommend d where d.age =18) d2
result: 
             "{\"d2.age\":{}}",
            "{\"d2.age\":36}",
            "{\"d2.age\":36}",
            "{\"d2.age\":37}",

**Comment by cube2222** [comment]
As I said, I'm sorry but I can't help you unless you create a PR with the mongodb code.

**Comment by will2love** [comment]
sql :
select d2.children_num, d2.age, d2.user_id  from (select d.children_num, d.age, d.user_id from dws_recommend d where d.age =18) d2

result:
  "{\"d2.age\":18,\"d2.children_num\":1,\"d2.user_id\":\"e201e731ae1a469d88e625f4d26bc9c0\"}",
    {\"d2.age\":18,\"d2.children_num\":0,\"d2.user_id\":\"103c42273f64458d8e2a332cefe2c5ca\"}",


its result is successful.
why sub query must is select xxx, yyy , it seems not to support  select * when sub query

**Comment by cube2222** [comment]
As I said, I'm sorry but I can't help you unless you create a PR with the mongodb code.
