### ISSUE TITLE
Framework and Design details

### ISSUE THREAD

**Issue by will2love** [cube2222/octosql#156]
hi, I want to know the specific process how execute Physical plan. Do you have any reference materials？
I  want to  know the details of logical plan convert to Physical plan, and then how execute Physical plan. 
thanks

**Comment by cube2222** [comment]
You just have to read the code for now. There's a package logical with the logical plan components, which then construct the physical one, which gets transformed by the optimizer, and later the physical plan knows how to construct an execution plan from itself.
