### ISSUE TITLE
go get installation broken on latest

### ISSUE THREAD

**Issue by rhanberry** [cube2222/octosql#165]
when you run go get as specified in docs the following error message occurs: `# github.com/cube2222/octosql/storage/excel
go/src/github.com/cube2222/octosql/storage/excel/datasource.go:145:9: assignment mismatch: 1 variable but rs.rows.Columns returns 2 values
go/src/github.com/cube2222/octosql/storage/excel/datasource.go:162:11: assignment mismatch: 1 variable but rs.rows.Columns returns 2 values
go/src/github.com/cube2222/octosql/storage/excel/excel.go:26:8: undefined: excelize.TitleToNumber
`

**Comment by cube2222** [comment]
What version of go do you have?

**Comment by cube2222** [comment]
Ok, I've been able to reproduce this. You need to run go get with go modules on, I'll add this to the README, please let me know if this fixes it for you:
```
GO111MODULE=on go get -v github.com/cube2222/octosql/cmd/octosql
```

**Comment by rhanberry** [comment]
Hey that worked! Thank you!!!
