### ISSUE TITLE
I like octosql, I would gladly contribute my efforts，I want to complete Visualizer with graphviz

### ISSUE THREAD

**Issue by runner-mei** [cube2222/octosql#203]
- [x] 1.  all Node type of logical.  #204
- [x] 2.  ~~all Node type of physical.~~
- [x] 2. add visualize cmd #205

**Comment by cube2222** [comment]
Great to hear that! 🙂

Are there any types of physical nodes which are currently not visualized?

Anyways, feel free to work on this, nobody is currently working on it afaik, and feel free to open an early WIP pull request, so we can stay connected while you work on it!

**Comment by runner-mei** [comment]
https://github.com/runner-mei/octosql/commit/638fece867b71f067898cfd8097b308ead99bb9c
