### ISSUE TITLE
[ENHANCE] unix domain socket path too long

### ISSUE THREAD

**Issue by xqbumu** [cube2222/octosql#271]
If the length of socketPath exceeds 107, the listener will fail to be created, so we could:

1. replace ulid with others, or change the rule of tmp dir
2. add a config argument to set octosql's data dir
3. or other methods

https://github.com/cube2222/octosql/blob/9ef95ec464564c7c4f4dbd2c32d3485a0ff5323c/plugins/plugins.go#L112-L118

refer: https://github.com/golang/go/issues/43635

**Comment by cube2222** [comment]
Thanks for raising the issue! I'll look into it.

**Comment by cube2222** [comment]
Hey! This is now added. You can customize the plugin tmp dir using the OCTOSQL_PLUGIN_TMP_DIR environment variable. I'll consider adding a flag for this in the future.
