### ISSUE TITLE
[bug] doesn't read some csvs?

### ISSUE THREAD

**Issue by indigoviolet** [cube2222/octosql#290]
```
❯ head ../wikidata/P1056.csv                         
subject,subjectLabel,object,objectLabel
http://www.wikidata.org/entity/Q524931,coup de grâce,http://www.wikidata.org/entity/Q4,death
http://www.wikidata.org/entity/Q6437079,Krinos Foods,http://www.wikidata.org/entity/Q41,Greece
...

❯ octosql 'select * from ../wikidata/P1056.csv limit 10'

Error: couldn't parse query: invalid argument syntax error at position 16

❯ octosql -v                      
octosql version 0.9.2
```

**Comment by cube2222** [comment]
Hey @indigoviolet!

`../` is not supported in the bare form, you need to wrap the file path in backticks.

In other words

```
octosql 'select * from `../wikidata/P1056.csv` limit 10'
```

**Comment by cube2222** [comment]
I agree the syntax errors are absolutely atrocious. Unfortunately, error recovery and reporting is a hard problem in LR1 parsers (which is what OctoSQL uses), though CockroachDB has some interesting blog posts around it, as they managed to solve that problem.

This is definitely something to improve in the future.
