### ISSUE TITLE
queries using filenames that start with non-alpha characters fail

### ISSUE THREAD

**Issue by protectroot-com** [cube2222/octosql#309]
$ sha256sum a.json                                                         
4518d5db3dedeaf5b8cf078d8090b5d3d8b2da6befe9cddbf0544d4f3e61cb45  a.json

$ sha256sum 1.json                                                         
4518d5db3dedeaf5b8cf078d8090b5d3d8b2da6befe9cddbf0544d4f3e61cb45  1.json

$ ~/go/bin/octosql "select 'works' from a.json limit 1"
+---------+
|  col_0  |
+---------+
| 'works' |
+---------+

$ ~/go/bin/octosql "select 'sad face' from 1.json limit 1"
Usage:
  octosql <query> [flags]
  octosql [command]

Examples:
octosql "SELECT * FROM myfile.json"
octosql "SELECT * FROM mydir/myfile.csv"
octosql "SELECT * FROM plugins.plugins"

**Comment by protectroot-com** [comment]
Seeing the same issue with filename a.b.json

$ ~/go/bin/octosql "select 'sad face' from a.b.json limit 1"
Usage:
  octosql <query> [flags]
  octosql [command]

Examples:
octosql "SELECT * FROM myfile.json"
octosql "SELECT * FROM mydir/myfile.csv"
octosql "SELECT * FROM plugins.plugins"

**Comment by protectroot-com** [comment]
strangely my go to consolidated file name, all.json doesn't work either.

**Comment by cube2222** [comment]
Hey @protectroot-com!

You can use double quotes for names which aren't accepted as-is.

So \"1.json\" in your case.

**Comment by cube2222** [comment]
Closing for now. Feel free to reopen.
