### ISSUE TITLE
Add charindex(String, String) function

### ISSUE THREAD

**Issue by dwisiswant0** [cube2222/octosql#325]

**Comment by cube2222** [comment]
How would that differ from the current `position` function @dwisiswant0?

**Comment by dwisiswant0** [comment]
> How would that differ from the current `position` function @dwisiswant0?

In my case, I don't know why I always got the error when using that function.

```console
> octosql "SELECT POSITION('.' IN 'github.com')"
...
Error: couldn't parse query: invalid argument syntax error at position 36 near 'github.com'
```

**Comment by dwisiswant0** [comment]
> > How would that differ from the current `position` function @dwisiswant0?
> 
> In my case, I don't know why I always got the error when using that function.
> 
> ```
> > octosql "SELECT POSITION('.' IN 'github.com')"
> ...
> Error: couldn't parse query: invalid argument syntax error at position 36 near 'github.com'
> ```

Oh, I get it now. It should be:
```sql
SELECT POSITION('github.com', '.')
```

Lil' bit confusing for me.
